//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDXWinForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDXWinForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_1_____Grid_and_Camera_Movement_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_1_____Grid_and_Camera_Movement_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_10___Sky_Domes_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_10___Sky_Domes_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_11___Bitmap_Clouds_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_11___Bitmap_Clouds_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_12___Perturbed_Clouds_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_12___Perturbed_Clouds_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_13___Terrain_Detail_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_13___Terrain_Detail_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_14___Slope_Based_Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_14___Slope_Based_Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_15___Terrain_Bump_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_15___Terrain_Bump_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_16___Small_Body_Water_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_16___Small_Body_Water_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_17___Terrain_Texture_Layers_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_17___Terrain_Texture_Layers_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_19___Foliages_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_19___Foliages_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_2_____Height_Mapst_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_2_____Height_Mapst_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_3_____Terrain_Lightingt_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_3_____Terrain_Lightingt_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_4_____Terrain_Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_4_____Terrain_Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_5_____Quad_Trees_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_5_____Quad_Trees_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_6_____Height_Based_Movement_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_6_____Height_Based_Movement_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_7_____Color_Mapped_Terrain_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_7_____Color_Mapped_Terrain_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_8_____Terrain_Mini_Maps_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_8_____Terrain_Mini_Maps_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Terrain_Tutorial_9_____Terrain_Blending_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Terrain_Tutorial_9_____Terrain_Blending_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_10___Specular_Lighting_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_10___Specular_Lighting_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_11___2D_Rendering_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_11___2D_Rendering_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_12___Font_Engine_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_12___Font_Engine_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_13___Direct_Input_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_13___Direct_Input_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_14___Direct_Sound_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_14___Direct_Sound_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_15___FPS_CPU_Usage_And_Timers_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_15___FPS_CPU_Usage_And_Timers_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_16___Frustum_Culling_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_16___Frustum_Culling_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_17___MultiTexturing_And_TextureArrays_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_17___MultiTexturing_And_TextureArrays_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_18___Light_Maps_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_18___Light_Maps_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_19___Alpha_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_19___Alpha_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_2_____Creating_A_Framework_And_Window_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_2_____Creating_A_Framework_And_Window_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_20___Bump_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_20___Bump_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_21___Specular_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_21___Specular_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_22___Render_To_Texture_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_22___Render_To_Texture_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_23___Fog_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_23___Fog_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_24___Clipping_Planes_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_24___Clipping_Planes_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_25___Texture_Translation_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_25___Texture_Translation_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_26___Transparency_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_26___Transparency_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_27___Reflection_Projective_Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_27___Reflection_Projective_Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_28___Screen_Fades_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_28___Screen_Fades_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_29___Water_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_29___Water_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_3_____Initializing_DirectX_11_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_3_____Initializing_DirectX_11_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_30___Multiple_Point_Lights_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_30___Multiple_Point_Lights_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_31___3D_Sound_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_31___3D_Sound_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_32___Glass_And_Ice_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_32___Glass_And_Ice_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_33___Fire_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_33___Fire_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_34___Billboarding_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_34___Billboarding_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_35___Depth_Buffer_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_35___Depth_Buffer_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_36___Blur_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_36___Blur_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_37___Instancing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_37___Instancing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_38___Hardware_Tessellation_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_38___Hardware_Tessellation_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_39___Particle_Systems_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_39___Particle_Systems_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_4_____Buffers__Shaders__And_HLSL_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_4_____Buffers__Shaders__And_HLSL_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_40___Shadow_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_40___Shadow_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_41___Multiple_Light_Shadow_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_41___Multiple_Light_Shadow_Mapping_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_42___Soft_Shadows_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_42___Soft_Shadows_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_43___Projective_Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_43___Projective_Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_44___Projected_Light_Maps_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_44___Projected_Light_Maps_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_45___Managing_Multiple_Shaders_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_45___Managing_Multiple_Shaders_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_46___Glow_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_46___Glow_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_47___Picking_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_47___Picking_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_48___Directional_Shadow_Maps_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_48___Directional_Shadow_Maps_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_49___Shadow_Mapping_And_Transparency_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_49___Shadow_Mapping_And_Transparency_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_5_____Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_5_____Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_50___Deferred_Shading_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_50___Deferred_Shading_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_6_____Diffuse_Lighting_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_6_____Diffuse_Lighting_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_7_____3D_Mode_lRendering_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_7_____3D_Mode_lRendering_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_1____Tutorial_9_____Ambient_Lighting_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_1____Tutorial_9_____Ambient_Lighting_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_1_____Grid_and_Camera_Movement_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_2____Terrain_Tutorial_1_____Grid_and_Camera_Movement_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_10_____Terrain_Cell_Culling_Sm {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 10  -  Terrain Cell Culling Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_2_____Height_Mapst_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_2____Terrain_Tutorial_2_____Height_Mapst_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_3_____Terrain_Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_2____Terrain_Tutorial_3_____Terrain_Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_4_____Terrain_Lighting_Sm {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 4  -  Terrain Lighting Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_5_____Color_Mapped_Terrain_Sm {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 5  -  Color Mapped Terrain Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_6_____Terrain_Normal_Mapping_Sm {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 6  -  Terrain Normal Mapping Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_7___Sky_Domes_Sm_ {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 7 - Sky Domes Sm ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_8___RAW_Height_Mapss_Sm_ {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 8 - RAW Height Mapss Sm ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Terrain_Tutorial_9___Terrain_Cells_Sm_ {
            get {
                object obj = ResourceManager.GetObject("Series 2 -- Terrain Tutorial 9 - Terrain Cells Sm ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Series_2____Tutorial_5_____Texturing_Sm {
            get {
                object obj = ResourceManager.GetObject("Series_2____Tutorial_5_____Texturing_Sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
